### ISSUE TITLE
Large extruder refused to make gear

### ISSUE THREAD

**Issue by huneau** [Gregicality/gregicality#70] opened 2020-06-22 06:24 UTC
Large extruder refused to make gears while there was a form for rings in it, he actually made rings (it is strange that other different 7 inputs work fine)

**Comment by hjae78** [comment] 2020-06-22 10:17
Not sure what the issue was, seems to be working as intended for me. Put inputs in hatch with gear shape, makes gears, put input in hatch with ring shape, makes rings.

**Comment by huneau** [comment] 2020-06-22 17:09
Don't know, it's in gregicality Skyblock for someone. So I reported it

**Comment by hjae78** [comment] 2020-06-23 12:38
Talked to the user who reported it on discord and got some more information but still wasn't able to reproduce

**Comment by hjae78** [comment] 2020-08-12 09:32
Closing this for now as i couldn't replicate it

**Closed by hjae78** 2020-08-12 09:32 UTC
Labels: bug
