### ISSUE TITLE
Large Multi Use Machine don't work in Lathe model

### ISSUE THREAD

**Issue by nanmumc** [Gregicality/gregicality#475] opened 2021-05-02 03:01 UTC
broken after update from Gregicality-1.12.2-0.21.5.1 to Gregicality-1.12.2-0.22.1.jar

and, emitter block has no name.
![image](https://user-images.githubusercontent.com/25528572/116800656-b6988f80-ab35-11eb-99bb-134d8554ebef.png)

**Comment by nanmumc** [comment] 2021-05-03 07:24
And large Bending and Forming Machine do not work in Forming Press model 
version: Gregicality-1.12.2-0.22.2.jar

**Comment by nanmumc** [comment] 2021-05-06 10:24
The large machine can only  work in default model. 
Screwdriver can switch its model but it does not work.
This problem disturb me many days.
I am looking forward to a fix.

**Comment by DStrand1** [comment] 2021-05-22 17:23
Closing this as a duplicate of #457. We are looking into a fix for this hopefully as the next release. Additionally, the name issue for the component blocks has been fixed as of 0.22.3 or possibly earlier.

**Closed by DStrand1** 2021-05-22 17:23 UTC
Labels: bug
